// import axios from "axios";
import dbConnect from "../database/dbconnect";
// import CarRent from "../models/carRent";
import CarSale from "../models/carSale";
// import Individuals from "../models/individuals";

function Teste({ data }) {
  return <></>;
}

export default Teste;

export async function getServerSideProps() {
  const carsSale = [
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 50000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bad9",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 100000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bad9",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bad9",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bada",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 90000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bada",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 60000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244bada",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 20000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badb",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 70000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badb",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badb",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badc",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badc",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badc",
    },

    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badd",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badd",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4922266c44d73c244badd",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809a",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809a",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809a",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809b",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809b",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809b",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809c",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809c",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809c",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809d",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809d",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809d",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809e",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809e",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e809e",
    },
    {
      marque: "toyota",
      model: "avensis",
      fuel: "essence",
      transmission: "manuelle",
      type: "berline",
      annee: "2012",
      prix: 30000,
      constructor: "toyota",
      img: [
        "https://img.remediosdigitales.com/5e8f4b/toyota-avensis-2012-blanco-01/1366_2000.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e80a3",
    },
    {
      marque: "mazda",
      model: "cx-9",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2021",
      prix: 60000,
      constructor: "madza",
      img: [
        "https://tdrresearch.azureedge.net/photos/chrome/Expanded/White/2021MAS040170/2021MAS04017001.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e80a3",
    },
    {
      marque: "renault",
      model: "mégane",
      fuel: "essence",
      transmission: "automatique",
      type: "berline",
      annee: "2020",
      prix: 40000,
      constructor: "renault",
      img: [
        "https://www.largus.fr/images/images/configurateur-renault-megane-restylee-12.jpg",
      ],
      portiere: 4,
      foreign_key_partners: "63b4b9fd9672543f9e2e80a3",
    },
  ];

  dbConnect();

  // const indiv = await CarSale.insertMany(carsSale);
  // const r = await axios.post("http://localhost:3000/api/dealers", {
  //   dealers,
  // });
  return {
    props: {
      data: null,
    },
  };
}
